# Generated by Django 3.1.4 on 2020-12-24 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0002_post_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hidden_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_who_hid', to=settings.AUTH_USER_MODEL),
        ),
    ]
