# Generated by Django 3.1.4 on 2020-12-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedapp', '0003_auto_20201224_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_postted',
            new_name='date_posted',
        ),
    ]
